### PR TITLE
chore: add AREnableDoMoreOnArtsyRail and AREnableMeetYourNewAdvisorRail

### PR DESCRIPTION
**Pull request by dariakoko**
### Description

add AREnableDoMoreOnArtsyRail and AREnableMeetYourNewAdvisorRail
[CX-3600](https://artsyproduct.atlassian.net/browse/CX-3600)

### PR Checklist (tick all before merging)

- [x] I have not stored any sensitive keys/values/information in `Echo.json5` and in CI, or I have not changed anything in that file.

[CX-3600]: https://artsyproduct.atlassian.net/browse/CX-3600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by olerichter00 — COMMENTED** [review]
Shouldn't we just show one of these two rails on the home screen?

**Comment by dariakoko** [comment]
The ticket says to add two feature flags https://artsyproduct.atlassian.net/browse/CX-3600

**Comment by dariakoko** [comment]
Let me ask Pierluca tomorrow

**Comment by olerichter00** [comment]
True, the description is not very clear. The idea is to have a separate feature flag for each rail. Until the campaign starts, only the old rail is shown (which should now be set to true). On the day the campaign starts, we switch and set the flag to false for the old rail and true for the new rail.

Let me know if this makes sense to you or if you think we need to adjust something.

And this ticket would also include adding those two feature flags to Eigen, which will allow us to start the work on the home screen.

**Pull request merged**
