### PR TITLE
@ashfurrow: adds models and api/v1 endpoints for Message and Route models

### LINKED ISSUE #3: Accounts should have many Routes
Model should include
- [ ] name
- [ ] path

### LINKED ISSUE #4: Accounts should have many Messages
Model should include
- [ ] name
- [ ] content

### LINKED ISSUE #5: Clients with access to update the API should be able to CRUD Account Messages

### LINKED ISSUE #6: Clients with access to update the API should be able to CRUD Account Routes

### PR DESCRIPTION
**Pull request by dylanfareed**
There is some weirdness here that this project's models are soo similarly...modeled.

Closes #3 
Closes #4 
Closes #5
Closes #6

### CODE REVIEW

**Comment by ashfurrow** [comment]
If you add me as a collaborator, I can merge :)

**Comment by orta** [comment]
The mobile team has access :+1:

**Pull request merged**
