### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by artsyit**
This is an automatically generated release PR!

### CODE REVIEW

**Comment by pvinis** [comment]
(How cool would it be if horizon could automerge the deploys that dont change the file and dont deploy a file, and keep a pr waiting for the deploys with file changes 😃)

**Comment by ashfurrow** [comment]
Peril could do that!

**Comment by pvinis** [comment]
I wanted to play around with peril for personal repos, to test it out. Maybe some time I'll play around with it for echo 🤔. Until then, it's so few PRs that it doesn't matter much.

**Comment by ashfurrow** [comment]
Yeah! Do it! You can run a stripped-down Peril server with these setup docs: https://github.com/danger/peril/blob/master/docs/setup_for_org.md I do this for my own account (since GitHub accounts _are_ organizations) for things like vacation out-of-office responses: 

https://github.com/ashfurrow/peril-settings/blob/21976409314691323fe9b0f04207bf38f52a8614/rules/all-issues.ts#L28-L38

**Comment by pvinis** [comment]
Yea, I was inspired by your setup 😄

**Pull request merged**
