### PR TITLE
@orta: provides Account and Feature models/endpoints via Gris

### PR DESCRIPTION
**Pull request by dylanfareed**
First pass at #1 as there are many ways to skin that particular cat. Thinking about that phrase for a second. That's actually quite a terrifying image. Let's put cats aside for a moment. 

This PR introduces a very simple hypermedia API based on Artsy's [Gris](https://github.com/artsy/gris) framework. Where your issue asks for one endpoint, here we provide many. It presumes a chattier relationship between the API and clients but the boundaries are a bit cleaner IMO. 

I broke this out into two commits: 
* https://github.com/artsy/echo/commit/60f3a793fc0468ff344f8445a602caaeaa0c786c - basic Gris new app (aka `gris new echo`)
* https://github.com/artsy/echo/commit/29ad060464c8174ac7eb619ecae04c1bf113d3a6 - models and endpoints for Accounts and Features (also mostly standard gris generators `gris generate api feature` & `gris generate migration createFeatures`) 
* https://github.com/dylanfareed/echo/commit/acde8b6de7aa44750ccfe2b0825de09eb4961527 - diverges from basic vanilla gris setup to break the API into two versioned APIs using Grape's `header` strategy; calls with an `application/vnd.echo-v1+json` accept header will get API V1 (hypermedia full CRUD) while requests with `application/vnd.echo-v2+json` accept header will only have access to a single `/accounts/:id` endpoint into which can stuff everything.

Feel free to not merge this if it will be too burdensome to consume this kind of an API from your side of the fence, buddy.

### CODE REVIEW

**Comment by orta** [comment]
I don't want a chatty API, ideally I want to be able to make as few requests as possible as this has to happen on launch startup every time when networking isn't cheap. Ideally I'd like to be able to make a `HEAD` and compare dates and only downloads + runs if something has changed. 

I'm happy to merge and start moving it in this direction. Also, I know very little about hypermedia. Happy to do this over a quick `/hangout` but this is my plan of action

- [ ] Remove accounts, we don't need per-user access
- [ ] Add the other models like Features with their own routes
- [ ] Add a route that encompasses all the data
- [ ] make the head for that route return the most recent `updated_at` for all the returned data

Does this feel reasonable?

**Comment by dylanfareed** [comment]
Lets rap today. Accounts here aren't per-user but per-app. So Eigen would be one account and Energy would be another.

**Comment by orta** [comment]
ace, will ping you on a reasonable NYC time

**Comment by ashfurrow** [comment]
Coooooooooool

**Comment by dylanfareed** [comment]
@orta we could version the API so that the UI app that handles the CRUD could interact with the hypermedia v1. 

Your lazy apps could read from an orchestration-style v2. 

Lets go ahead and merge this.

**Comment by dylanfareed** [comment]
Thanks, @ashfurrow!

Updated in any case to provide a versioned API that supports both modes of use--CRUD hypermedia for management (V1) and just a single endpoint for wrapping all the goodies for each account (V2)--via accept header.

**Comment by orta** [comment]
OK, let's dooooo it

**Pull request merged**
