### PR TITLE
chore: disable upcoming auction results rail

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description
This PR addresses [Turn OFF "Upcoming auction lots for you" on the homefeed](https://artsyproduct.atlassian.net/browse/CX-3714)

### PR Checklist (tick all before merging)

- [x] I have not stored any sensitive keys/values/information in `Echo.json5` and in CI, or I have not changed anything in that file.

### CODE REVIEW

**Comment by egdbear** [comment]
cc @joeyAghion

**Comment by MounirDhahri** [comment]
this came on a good time 😄

**Comment by olerichter00** [comment]
> @egdbear this will cut half of the queries consuming the slow interface you raised https://github.com/artsy/eigen/pull/8689

Unfortunately, disabling the feature flag won't stop the query. We could use [GraphQL's `@skip`](https://dgraph.io/docs/graphql/queries/skip-include/#skip) directive to avoid executing when the feature flag is disabled

**Comment by MounirDhahri** [comment]
I was under the impression relay won't make the query unless the fragment is being required in runtime but I might be wrong. Anyway I think your comment is valid and I needed to remove the module from Eigen as well and it's what I did here https://github.com/artsy/eigen/pull/8806
I am removing it by requestion from Jack and Mike

**Pull request merged**
