### PR TITLE
[WIP] remove released feature flags

### PR DESCRIPTION
**Pull request by dariakoko**
### Description
Removed released feature flags:
- ARMyCollectionLocalSortAndFilter
- AREnableAuctionResultComparableWorks
- AREnableMyCollectionAndroid
- AREnableMyCollectionIOS

Tickets: [CX-2266], [CX-2267], [CX-2268]

### PR Checklist (tick all before merging)

- [ ] I have not stored any sensitive keys/values/information in `Echo.json5` and in CI, or I have not changed anything in that file.

[CX-2266]: https://artsyproduct.atlassian.net/browse/CX-2266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2267]: https://artsyproduct.atlassian.net/browse/CX-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2268]: https://artsyproduct.atlassian.net/browse/CX-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dariakoko** [comment]
Hi @pvinis, the usage of these feature flags is removed from eigen (tickets mentioned in the PR description, not merged yet).
Please, let me know if I removed feature flags wrong. The PR checklist made me thinking

**Comment by brainbicycle** [comment]
👋 I am not sure we can do this safely, I believe old clients will still be reading these flags and without them the value will default to false, effectively disabling the feature but we will want to test either way before merging.

**Comment by dariakoko** [comment]
> 👋 I am not sure we can do this safely, I believe old clients will still be reading these flags and without them the value will default to false, effectively disabling the feature but we will want to test either way before merging.

👋 I see, thanks for your response! Makes cense. I'm changing it to WIP then, and will talk to CX about it

**Comment by dariakoko** [comment]
discussed, should not remove them yet

**Pull request closed without merging**
